language: node_js

branches:
  only:
  - master

node_js:
  - "7.8"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g typescript firebase-tools @angular/cli
  - yarn install
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - npm run build

after_script:
  - firebase deploy --only hosting --token ${FIREBASE_TOKEN}

notifications:
  slack: scvodigital:EDHUnmQ8GlMOZpk2UBJ7yHjg