language: node_js

branches:
  only:
  - release

node_js:
  - "8.4"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g typescript firebase-tools
  - yarn install
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - npm run build

after_script:
  - firebase deploy --only hosting --token ${FIREBASE_TOKEN} --non-interactive

notifications:
  slack: scvodigital:EDHUnmQ8GlMOZpk2UBJ7yHjg
